### ISSUE TITLE
Set focus to first field on opening widget

### ISSUE THREAD

**Issue by MurzNN** [Qwertovsky/quick_url_addon#2]
At now after clicking on extension icon, we must manually click on field for set focus and start typing. Will be good to automate setting focus to first field on opening widget event. 

As example of implementation for setting focus to field, you can lookup [Bitwarden](https://addons.mozilla.org/ru/firefox/addon/bitwarden-password-manager/) extension source code.

**Comment by Qwertovsky** [comment]
Done
