### ISSUE TITLE
URL Templating

### ISSUE THREAD

**Issue by arndt-s** [Qwertovsky/quick_url_addon#3]
love this widget!
i'd suggest the url is templated via a placeholder in order to use parameters in the middle of the url.
for example `https://foo.bar/task/${param}/complete`.

**Comment by Qwertovsky** [comment]
FYI, with Firefox you can create bookmark for address `https://foo.bar/task/%s/complete` with key `foo`. Then you can open this address by typing `foo param` in the url field.

**Comment by Qwertovsky** [comment]
Done.
Use one or more placeholders.
Like this `https://foo.bar/task/{?}/complete?param={?}`
There is just one field for all parameters. So divide them by `/`.
If your URL somehow contains `{?}` encode it as `{%3F}`
